// Layered scope categories used to gate shortcut handlers. The actual route→scope
// mapping lives in the ShortcutProvider (a feature concern); this enum is shared so
// hooks and consumer code (dialogs, components) can name a scope without pulling from
// the feature module.
export enum ShortcutScope {
  GLOBAL = 'GLOBAL',
  GAME = 'GAME',
  DECK_EDITOR = 'DECK_EDITOR',
  ROOM = 'ROOM',
  REPLAYS = 'REPLAYS',
}

export type ShortcutHandler = (event: KeyboardEvent) => void;

export interface ShortcutRegistration {
  actionId: string;
  handler: ShortcutHandler;
  scope: ShortcutScope;
  preventDefault?: boolean;
}

export interface ParsedSequence {
  code: string;
  ctrl: boolean;
  shift: boolean;
  alt: boolean;
  meta: boolean;
}

export type ActionId =
  | 'chat.focus'
  | 'game.untapAll'
  | 'game.drawCard'
  | 'game.drawMultipleCards'
  | 'game.undoDraw'
  | 'game.endTurn'
  | 'game.concede'
  | 'game.shuffleLibrary'
  | 'game.nextPhase'
  | 'game.prevPhase'
  | 'game.nextPhaseAction'
  | 'game.reverseTurn'
  | 'game.rotateViewCW'
  | 'game.rotateViewCCW'
  | 'game.rollDice'
  | 'game.leaveGame'
  | 'game.viewSideboard'
  | 'game.mulliganSameSize'
  | 'game.mulliganMinusOne'
  | 'game.sortHandByType'
  | 'game.viewLibrary'
  | 'game.viewGraveyard'
  | 'game.playTop'
  | 'game.moveTopToGrave'
  | 'game.moveTopNToGrave'
  | 'game.closeRecentView'
  | 'game.flipCoin'
  | 'game.doesntUntap'
  | 'game.flipCard'
  | 'game.unattachCard'
  | 'game.cloneCard'
  | 'game.revealSelectedToAll'
  | 'game.hideRevealedCard'
  | 'game.sayMacro1'
  | 'game.sayMacro2'
  | 'game.sayMacro3'
  | 'game.sayMacro4'
  | 'game.sayMacro5'
  | 'game.sayMacro6'
  | 'game.sayMacro7'
  | 'game.sayMacro8'
  | 'game.sayMacro9'
  | 'game.sayMacro10'
  | 'game.moveSelectedToGrave'
  | 'game.moveSelectedToLibraryBottom'
  | 'game.setCardPT'
  | 'game.incP'
  | 'game.decP'
  | 'game.incT'
  | 'game.decT'
  | 'game.incPT'
  | 'game.decPT'
  | 'game.setAnnotation'
  | 'game.selectAllBattlefield'
  | 'game.selectRowBattlefield'
  | 'game.selectColumnBattlefield'
  | 'game.incrementAllCardCounters'
  | 'game.addCounterA'
  | 'game.removeCounterA'
  | 'game.setCounterA'
  | 'game.addCounterB'
  | 'game.removeCounterB'
  | 'game.setCounterB'
  | 'game.addCounterC'
  | 'game.removeCounterC'
  | 'game.setCounterC'
  | 'game.peekCard'
  | 'game.attachCard'
  | 'game.addStormCounter'
  | 'game.removeStormCounter'
  | 'game.setStormCounter'
  | 'game.moveTopUntil'
  | 'game.alwaysRevealTopCard'
  | 'game.alwaysLookAtTopCard'
  | 'game.viewTopCards'
  | 'game.viewBottomCards'
  | 'game.createToken'
  | 'game.createAnotherToken'
  | 'game.drawArrow'
  | 'game.resetPT'
  | 'game.reduceLifeByPower'
  | 'game.mulligan'
  | 'game.setLife'
  | 'game.removeLocalArrows'
  | 'game.tapCard'
  | 'game.playCard'
  | 'game.playCardFaceDown'
  | 'game.createRelatedTokens'
  | 'game.moveSelectedToExile'
  | 'game.moveSelectedToHand'
  | 'game.moveSelectedToLibraryTop'
  | 'game.moveSelectedToBattlefield'
  | 'game.viewHand'
  | 'game.viewExile'
  | 'game.sortHandByName'
  | 'game.sortHandByManaValue'
  | 'game.revealHandToAll'
  | 'game.revealRandomHandCardToAll'
  | 'game.moveTopToPlayFaceDown'
  | 'game.moveTopNToGraveFaceDown'
  | 'game.moveTopToExile'
  | 'game.moveTopNToExile'
  | 'game.moveTopNToExileFaceDown'
  | 'game.moveTopToBottom'
  | 'game.moveBottomToPlay'
  | 'game.moveBottomToPlayFaceDown'
  | 'game.moveBottomToGrave'
  | 'game.moveBottomNToGrave'
  | 'game.moveBottomNToGraveFaceDown'
  | 'game.moveBottomToExile'
  | 'game.moveBottomNToExile'
  | 'game.moveBottomNToExileFaceDown'
  | 'game.moveBottomToTop'
  | 'game.drawBottomCard'
  | 'game.drawBottomCards'
  | 'game.shuffleTopCards'
  | 'game.shuffleBottomCards'
  | 'game.addCounterD'
  | 'game.removeCounterD'
  | 'game.setCounterD'
  | 'game.addCounterE'
  | 'game.removeCounterE'
  | 'game.setCounterE'
  | 'game.addCounterF'
  | 'game.removeCounterF'
  | 'game.setCounterF'
  | 'game.incLife'
  | 'game.decLife'
  | 'game.incManaCounterW'
  | 'game.decManaCounterW'
  | 'game.setManaCounterW'
  | 'game.incManaCounterU'
  | 'game.decManaCounterU'
  | 'game.setManaCounterU'
  | 'game.incManaCounterB'
  | 'game.decManaCounterB'
  | 'game.setManaCounterB'
  | 'game.incManaCounterR'
  | 'game.decManaCounterR'
  | 'game.setManaCounterR'
  | 'game.incManaCounterG'
  | 'game.decManaCounterG'
  | 'game.setManaCounterG'
  | 'game.incManaCounterX'
  | 'game.decManaCounterX'
  | 'game.setManaCounterX'
  | 'game.flowP'
  | 'game.flowT'
  | 'game.setPhase0'
  | 'game.setPhase1'
  | 'game.setPhase2'
  | 'game.setPhase3'
  | 'game.setPhase4'
  | 'game.setPhase5'
  | 'game.setPhase6'
  | 'game.setPhase7'
  | 'game.setPhase8'
  | 'game.setPhase9'
  | 'game.setPhase10'
  | 'deck.new'
  | 'deck.save'
  | 'deck.load'
  | 'deck.addCard'
  | 'deck.removeCard'
  | 'deck.undo'
  | 'deck.redo'
  | 'room.sendMessage'
  | 'replays.playPause'
  | 'replays.skipForward'
  | 'replays.skipBackward'
  | 'replays.skipForwardBig'
  | 'replays.skipBackwardBig'
  | 'replays.toggleFastForward';

export type ShortcutGroupId =
  | 'game'
  | 'gameCardCounters'
  | 'gamePlayerCounters'
  | 'gamePowerToughness'
  | 'gamePhases'
  | 'gamePlayingArea'
  | 'gameMoveSelected'
  | 'gameView'
  | 'gameMoveTop'
  | 'gameMoveBottom'
  | 'gameplay'
  | 'gameDrawing'
  | 'gameHand'
  | 'deckEditor'
  | 'room'
  | 'replays';

export interface ShortcutDef {
  scope: ShortcutScope;
  group: ShortcutGroupId;
  sequences: string[];
}
