export type ColorScheme = 'light' | 'dark';

export type PaletteToken =
  | 'bg-base'
  | 'bg-surface'
  | 'bg-elevated'
  | 'border-subtle'
  | 'border-strong'
  | 'border-control'
  | 'accent-primary'
  | 'accent-primary-hover'
  | 'accent-secondary'
  | 'text-on-accent'
  | 'text-primary'
  | 'text-secondary'
  | 'text-muted'
  | 'text-disabled'
  | 'status-danger'
  | 'status-success'
  | 'status-warning'
  | 'seat-flash-gain'
  | 'seat-flash-loss'
  | 'seat-select'
  | 'seat-attach'
  | 'seat-doesnt-untap'
  | 'over-art-text'
  | 'over-art-backdrop'
  | 'over-art-life'
  | 'pt-modified'
  | 'mana-w'
  | 'mana-u'
  | 'mana-b'
  | 'mana-r'
  | 'mana-g'
  | 'mana-c'
  | 'mana-o';

export type Palette = Readonly<Record<PaletteToken, string>>;

export const PALETTES: Readonly<Record<ColorScheme, Palette>> = {
  dark: {
    'bg-base': '#14101F',
    'bg-surface': '#1F1830',
    'bg-elevated': '#2A2140',
    'border-subtle': '#3A2E5A',
    'border-strong': '#5A4A85',
    'border-control': '#7C6AA8',
    'accent-primary': '#9F7AEA',
    'accent-primary-hover': '#B794F4',
    'accent-secondary': '#6B46C1',
    'text-on-accent': '#14101F',
    'text-primary': '#F5F0F6',
    'text-secondary': '#C7BFD4',
    'text-muted': '#9388A5',
    'text-disabled': '#A89EA5',
    'status-danger': '#F87171',
    'status-success': '#34D399',
    'status-warning': '#FACC15',
    'seat-flash-gain': '#34E07A',
    'seat-flash-loss': '#EF4444',
    'seat-select': '#3B82F6',
    'seat-attach': '#22C55E',
    'seat-doesnt-untap': '#FBBF24',
    'over-art-text': '#FFFFFF',
    'over-art-backdrop': '#000000',
    'over-art-life': '#F87171',
    'pt-modified': '#FF9600',
    'mana-w': '#F9F1C8',
    'mana-u': '#3B82F6',
    'mana-b': '#4B5563',
    'mana-r': '#EF4444',
    'mana-g': '#10B981',
    'mana-c': '#9CA3AF',
    'mana-o': '#F97316',
  },
  light: {
    'bg-base': '#F6F3FA',
    'bg-surface': '#FFFFFF',
    'bg-elevated': '#EEE9F5',
    'border-subtle': '#DCD3E9',
    'border-strong': '#B4A6CF',
    'border-control': '#857799',
    'accent-primary': '#6B46C1',
    'accent-primary-hover': '#553C9A',
    'accent-secondary': '#6B46C1',
    'text-on-accent': '#FFFFFF',
    'text-primary': '#1D1630',
    'text-secondary': '#463C5C',
    'text-muted': '#675D7E',
    'text-disabled': '#857D84',
    'status-danger': '#B91C1C',
    'status-success': '#047857',
    'status-warning': '#8A5905',
    'seat-flash-gain': '#34E07A',
    'seat-flash-loss': '#EF4444',
    'seat-select': '#3B82F6',
    'seat-attach': '#15803D',
    'seat-doesnt-untap': '#B45309',
    'over-art-text': '#FFFFFF',
    'over-art-backdrop': '#000000',
    'over-art-life': '#F87171',
    'pt-modified': '#FF9600',
    'mana-w': '#F9F1C8',
    'mana-u': '#3B82F6',
    'mana-b': '#4B5563',
    'mana-r': '#EF4444',
    'mana-g': '#10B981',
    'mana-c': '#9CA3AF',
    'mana-o': '#F97316',
  },
};
